# Generated by Django 5.2.1 on 2025-05-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('specific', 'Specific'), ('flexible', 'Flexible')], default='specific', max_length=20)),
                ('flexible_schedule_days', models.JSONField(blank=True, null=True)),
                ('flexible_time_slots', models.JSONField(blank=True, null=True)),
                ('budget_type', models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed')], max_length=20)),
                ('budget_min_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_qualifications', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('matched_provider_id', models.IntegerField(blank=True, null=True)),
                ('auto_expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(db_column='service_type', on_delete=django.db.models.deletion.CASCADE, to='service_app.servicecategory', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('estimated_duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('materials', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_expire_at', models.DateTimeField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='service_app.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='service_request_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_app.servicerequest')),
            ],
        ),
    ]
