# Generated by Django 5.2.1 on 2025-05-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='created_by_user_id',
        ),
    ]
