# Generated by Django 5.2 on 2025-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_servicerequest_flexible_schedule_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='flexible_schedule_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='flexible_time_slots',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='preferred_qualifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
