# Generated by Django 5.2 on 2025-05-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_servicerequest_flexible_schedule_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('estimated_duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('materials', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_expire_at', models.DateTimeField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='service_app.servicerequest')),
            ],
        ),
    ]
