# Generated by Django 5.2 on 2025-05-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffer',
            old_name='request',
            new_name='request_id',
        ),
    ]
