# Generated by Django 5.1 on 2025-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('note', models.TextField()),
                ('state', models.IntegerField(choices=[('unread', 'Unread'), ('read', 'Read')], default=0)),
                ('type', models.IntegerField(choices=[('offer', 'Offer'), ('order', 'Order'), ('End Request', 'End Request'), ('Start Request', 'Start Request')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
