# Generated by Django 5.0.3 on 2025-05-26 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('service_provider', 'Service Provider'), ('administrator', 'Administrator')], default='customer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customuser',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lag', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='User.custom_user')),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='TechnicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceCategories', models.JSONField(blank=True, default=list)),
                ('serviceRegions', models.JSONField(blank=True, default=list)),
                ('employeeCount', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('availability', models.JSONField(blank=True, default=list)),
                ('yearsInBusiness', models.CharField(max_length=255)),
                ('service', models.ManyToManyField(related_name='technical_profiles', to='User.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_profile', to='User.custom_user')),
            ],
            options={
                'db_table': 'TechnicalProfile',
            },
        ),
    ]
