# Generated by Django 5.2 on 2025-05-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_by_user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('description', models.TextField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('additional_location_info', models.TextField(blank=True, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('flexible_schedule_days', models.JSONField(blank=True, null=True)),
                ('flexible_time_slots', models.JSONField(blank=True, null=True)),
                ('budget_min_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max_hourly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_price_offer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('matched_provider_id', models.IntegerField(blank=True, null=True)),
                ('auto_expire_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='service_app.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='service_request_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_app.servicerequest')),
            ],
        ),
    ]
