# Generated by Django 5.2 on 2025-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='additional_location_info',
            new_name='additionalInfo',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='flexible_schedule_days',
            new_name='flexibleDays',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='flexible_time_slots',
            new_name='flexibleTimes',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='preferred_date',
            new_name='preferredDate',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='preferred_time',
            new_name='preferredTime',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='state',
            new_name='region',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferredQualifications',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
