# Generated by Django 5.2 on 2025-05-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_rename_request_serviceoffer_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoffer',
            old_name='request_id',
            new_name='request',
        ),
    ]
